#!/usr/bin/env node

// Repo-side, dev-time sync of the shared font pool (registry/fonts/) from the
// pinned @fontsource-variable/* devDependencies.
//
// Each family directory receives the latin variable-weight woff2, that
// family's own OFL.txt (families have separate copyright holders, so per-item
// license shipping is a license requirement, not a nicety), a generated
// README, and a generated registry-item.json. Styles depend on families via
// registryDependencies, so `add`/`init` copies a shared family into a deck
// exactly once.
//
// Rerun after bumping a @fontsource-variable dependency; commit the result.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

// name: registry item suffix + directory; pkg: @fontsource-variable package;
// family: the CSS font-family name registered by the @font-face rule.
export const FONT_FAMILIES = [
  { name: "fraunces", pkg: "fraunces", family: "Fraunces Variable" },
  { name: "newsreader", pkg: "newsreader", family: "Newsreader Variable" },
  { name: "source-serif-4", pkg: "source-serif-4", family: "Source Serif 4 Variable" },
  { name: "inter", pkg: "inter", family: "Inter Variable" },
  { name: "space-grotesk", pkg: "space-grotesk", family: "Space Grotesk Variable" },
  { name: "libre-franklin", pkg: "libre-franklin", family: "Libre Franklin Variable" },
  { name: "jetbrains-mono", pkg: "jetbrains-mono", family: "JetBrains Mono Variable" },
  {
    name: "bricolage-grotesque",
    pkg: "bricolage-grotesque",
    family: "Bricolage Grotesque Variable",
  },
];

const root = path.resolve(import.meta.dirname, "..");

function fontFilePath(name) {
  return `registry/fonts/${name}/${name}-latin-wght-normal.woff2`;
}

function fontFaceCss(entry, weightRange) {
  return `@font-face {
  font-family: "${entry.family}";
  font-style: normal;
  font-display: block;
  font-weight: ${weightRange};
  src: url("./${entry.name}-latin-wght-normal.woff2") format("woff2-variations");
}
`;
}

function registryItem(entry, version) {
  return {
    name: `fonts/${entry.name}`,
    type: "ls:font",
    status: "preview",
    title: entry.family.replace(/ Variable$/, ""),
    description: `${entry.family.replace(/ Variable$/, "")} variable webfont (latin, wght axis), vendored from @fontsource-variable/${entry.pkg}@${version} under the SIL Open Font License 1.1.`,
    files: [
      { path: fontFilePath(entry.name), type: "registry:font" },
      { path: `registry/fonts/${entry.name}/font.css`, type: "registry:style" },
      { path: `registry/fonts/${entry.name}/OFL.txt`, type: "registry:license" },
    ],
    registryDependencies: [],
    dependencies: [],
    devDependencies: [],
    docs: `registry/fonts/${entry.name}/README.md`,
    agentLevel: "advanced",
    authoring: {
      usage: [
        `Loaded via the family @font-face in font.css; reference it through style tokens, not directly. The registered font-family name is "${entry.family}".`,
      ],
    },
  };
}

function readme(entry, version) {
  const title = entry.family.replace(/ Variable$/, "");
  return `# ${title}

Vendored variable webfont (latin subset, \`wght\` axis) from \`@fontsource-variable/${entry.pkg}\` ${version}.

- Registered \`font-family\`: \`"${entry.family}"\`
- License: SIL Open Font License 1.1 (see \`OFL.txt\` in this directory)
- Generated by \`scripts/fonts-sync.mjs\` — do not edit by hand.

Styles depend on this family via \`registryDependencies\`; decks load it through the style's \`font.css\` link, never a CDN.
`;
}

async function syncFamily(entry) {
  const pkgRoot = path.join(root, "node_modules", "@fontsource-variable", entry.pkg);
  const pkg = JSON.parse(await readFile(path.join(pkgRoot, "package.json"), "utf8"));
  const metadata = JSON.parse(await readFile(path.join(pkgRoot, "metadata.json"), "utf8"));
  const weights = metadata.variable?.wght
    ? `${metadata.variable.wght.min} ${metadata.variable.wght.max}`
    : "100 900";
  const woff2 = await readFile(path.join(pkgRoot, "files", `${entry.pkg}-latin-wght-normal.woff2`));
  const license = await readFile(path.join(pkgRoot, "LICENSE"), "utf8");

  const dir = path.join(root, "registry", "fonts", entry.name);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, `${entry.name}-latin-wght-normal.woff2`), woff2);
  await writeFile(path.join(dir, "OFL.txt"), license);
  await writeFile(path.join(dir, "font.css"), fontFaceCss(entry, weights));
  await writeFile(path.join(dir, "README.md"), readme(entry, pkg.version));
  await writeFile(
    path.join(dir, "registry-item.json"),
    `${JSON.stringify(registryItem(entry, pkg.version), null, 2)}\n`,
  );
  return { name: entry.name, version: pkg.version, bytes: woff2.length };
}

const results = [];
for (const entry of FONT_FAMILIES) {
  results.push(await syncFamily(entry));
}
const total = results.reduce((sum, result) => sum + result.bytes, 0);
for (const result of results)
  console.log(
    `fonts-sync: ${result.name} ${result.version} (${Math.round(result.bytes / 1024)} KB)`,
  );
console.log(`fonts-sync: ${results.length} families, ${Math.round(total / 1024)} KB woff2 total.`);
console.log("fonts-sync: remember to list new fonts/<name> items in registry.json.");
process.exit(0);
